/**
 * Seed Exercise Library
 * 
 * This is the curated default exercise library that ships with every new coach account.
 * Coaches can add demo video links themselves and also add their own custom exercises.
 * 
 * Categories covered: Stretching/Mobility, Strength, HIIT, Cross Training
 * 
 * Each exercise uses the same data shape as the exercise_library (templates table with
 * type='day', category='__exercise_library__').
 */

export type ExerciseCategory = 'stretching' | 'strength' | 'hiit' | 'cross'

export const EXERCISE_CATEGORY_LABELS: Record<ExerciseCategory, string> = {
  stretching: 'Stretching/Mobility',
  strength: 'Strength',
  hiit: 'HIIT',
  cross: 'Cross Training',
}

export type SeedExercise = {
  name: string
  demoVideo: string
  defaultMeasureType: 'reps' | 'time' | 'distance'
  defaultMeasureValue: string
  defaultSets: number
  defaultRest: string
  defaultWeight: string
  defaultWeightUnit: 'kg' | 'lbs'
  defaultNotes: string
  is_seed?: boolean
  categories: ExerciseCategory[]
}

// ─── STRETCHING / MOBILITY ───────────────────────────────────────────────────

const stretchingExercises: SeedExercise[] = [
  {
    name: 'Hip Flexor Stretch',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Keep hips square, gently push forward.',
    categories: ['stretching'],
  },
  {
    name: 'Pigeon Stretch',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:45',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Sink into the stretch gradually.',
    categories: ['stretching'],
  },
  {
    name: 'Hamstring Stretch (Standing)',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Hinge at hips, keep back flat.',
    categories: ['stretching'],
  },
  {
    name: 'Quad Stretch (Standing)',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Keep knees together, hold something for balance if needed.',
    categories: ['stretching'],
  },
  {
    name: 'Calf Stretch (Wall)',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Straight back leg, heel pressed down.',
    categories: ['stretching'],
  },
  {
    name: 'Cat-Cow',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Slow controlled movement. Breathe in on cow, out on cat.',
    categories: ['stretching'],
  },
  {
    name: 'World\'s Greatest Stretch',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '5',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Lunge, rotate, reach. Full range of motion.',
    categories: ['stretching'],
  },
  {
    name: 'Thoracic Spine Rotation',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. On all fours, hand behind head, rotate open.',
    categories: ['stretching'],
  },
  {
    name: 'Foam Roll — IT Band',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:45',
    defaultSets: 1,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Slow rolls from hip to just above knee.',
    categories: ['stretching'],
  },
  {
    name: 'Foam Roll — Quads',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:45',
    defaultSets: 1,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Face down. Roll from hip to above kneecap.',
    categories: ['stretching'],
  },
  {
    name: 'Foam Roll — Upper Back',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:45',
    defaultSets: 1,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Arms crossed over chest. Roll mid to upper back.',
    categories: ['stretching'],
  },
  {
    name: '90/90 Hip Stretch',
    demoVideo: 'https://www.youtube.com/watch?v=VYvMMw8z3rE',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Sit tall, lean into front hip.',
    categories: ['stretching'],
  },
  {
    name: 'Downward Dog',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Pedal feet to loosen calves. Push hips high.',
    categories: ['stretching'],
  },
  {
    name: 'Banded Shoulder Dislocates',
    demoVideo: 'https://www.youtube.com/watch?v=a9rqTzZaI7s',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Wide grip. Slow controlled arc over and behind head.',
    categories: ['stretching'],
  },
]

// ─── STRENGTH ────────────────────────────────────────────────────────────────

const strengthExercises: SeedExercise[] = [
  {
    name: 'Barbell Back Squat',
    demoVideo: 'https://www.youtube.com/watch?v=rrJIyZGlK8c',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 4,
    defaultRest: '02:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Brace core. Break at hips and knees together. Depth to parallel or below.',
    categories: ['strength'],
  },
  {
    name: 'Goblet Squat',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Hold dumbbell at chest. Elbows inside knees at bottom.',
    categories: ['strength', 'cross'],
  },
  {
    name: 'Romanian Deadlift (RDL)',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Soft knees, hinge at hips. Feel stretch in hamstrings. Bar/DB stays close to legs.',
    categories: ['strength'],
  },
  {
    name: 'Conventional Deadlift',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '5',
    defaultSets: 4,
    defaultRest: '02:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Flat back, brace core. Drive through floor. Lockout hips at top.',
    categories: ['strength'],
  },
  {
    name: 'Walking Lunges',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each leg. Long stride, back knee close to floor.',
    categories: ['strength', 'cross'],
  },
  {
    name: 'Bulgarian Split Squat',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each leg. Rear foot elevated on bench. Upright torso.',
    categories: ['strength'],
  },
  {
    name: 'Bench Press (Barbell)',
    demoVideo: 'https://www.youtube.com/watch?v=9_JPTA3ie7k',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 4,
    defaultRest: '02:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Shoulder blades pinched. Bar to chest, drive up. Feet flat on floor.',
    categories: ['strength'],
  },
  {
    name: 'Dumbbell Bench Press',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Full range of motion. Control the descent.',
    categories: ['strength'],
  },
  {
    name: 'Overhead Press (Barbell)',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 3,
    defaultRest: '02:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Brace core tight. Press straight up, head through at top.',
    categories: ['strength'],
  },
  {
    name: 'Dumbbell Shoulder Press',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Seated or standing. Full lockout overhead.',
    categories: ['strength'],
  },
  {
    name: 'Bent-Over Row (Barbell)',
    demoVideo: 'https://www.youtube.com/watch?v=9Gf-Ourup_k',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Hinge forward ~45°. Pull to lower chest. Squeeze shoulder blades.',
    categories: ['strength'],
  },
  {
    name: 'Single-Arm Dumbbell Row',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each arm. Pull elbow back past torso. No rotation.',
    categories: ['strength'],
  },
  {
    name: 'Pull-Ups',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 3,
    defaultRest: '02:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Full hang to chin over bar. Control the descent.',
    categories: ['strength', 'cross'],
  },
  {
    name: 'Lat Pulldown',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Wide grip. Pull to upper chest. Squeeze lats at bottom.',
    categories: ['strength'],
  },
  {
    name: 'Hip Thrust',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Upper back on bench. Drive hips to full extension. Squeeze glutes at top.',
    categories: ['strength'],
  },
  {
    name: 'Leg Press',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Feet shoulder width. Full depth without lower back lifting.',
    categories: ['strength'],
  },
  {
    name: 'Calf Raises (Standing)',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '15',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Full range — stretch at bottom, pause at top. Slow tempo.',
    categories: ['strength'],
  },
  {
    name: 'Face Pulls',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '15',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Pull to eye level, externally rotate at end. Light weight, squeeze rear delts.',
    categories: ['strength'],
  },
  {
    name: 'Lateral Raises',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Slight bend in elbows. Raise to shoulder height, control down.',
    categories: ['strength'],
  },
  {
    name: 'Bicep Curls (Dumbbell)',
    demoVideo: 'https://www.youtube.com/watch?v=6DeLZ6cbgWQ',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'No swinging. Full extension at bottom, squeeze at top.',
    categories: ['strength'],
  },
  {
    name: 'Tricep Dips',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Bench dips or parallel bars. Elbows back, not flared.',
    categories: ['strength', 'cross'],
  },
]

// ─── HIIT ────────────────────────────────────────────────────────────────────

const hiitExercises: SeedExercise[] = [
  {
    name: 'Burpees',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Chest to floor, jump at top. Keep moving.',
    categories: ['hiit', 'cross'],
  },
  {
    name: 'Mountain Climbers',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Fast pace. Hips level, core tight.',
    categories: ['hiit', 'cross'],
  },
  {
    name: 'Jump Squats',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Squat to parallel, explode up. Soft landing.',
    categories: ['hiit'],
  },
  {
    name: 'Box Jumps',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Land softly with both feet fully on box. Step down.',
    categories: ['hiit', 'cross'],
  },
  {
    name: 'Kettlebell Swings',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '15',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Hip hinge, not a squat. Snap hips forward. Arms are just along for the ride.',
    categories: ['hiit', 'strength', 'cross'],
  },
  {
    name: 'Battle Ropes — Alternating Waves',
    demoVideo: 'https://www.youtube.com/watch?v=ZujykKeVZpM',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Slight squat stance. Fast alternating arms. Keep waves consistent.',
    categories: ['hiit', 'cross'],
  },
  {
    name: 'High Knees',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Drive knees to hip height. Pump arms. Stay on balls of feet.',
    categories: ['hiit'],
  },
  {
    name: 'Tuck Jumps',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Jump and drive knees to chest. Land soft.',
    categories: ['hiit'],
  },
  {
    name: 'Skater Jumps',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '00:45',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side counts as 1. Bound laterally, land on one leg.',
    categories: ['hiit', 'cross'],
  },
  {
    name: 'Thruster (Dumbbell)',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Front squat into overhead press in one fluid movement.',
    categories: ['hiit', 'strength'],
  },
  {
    name: 'Sprint Intervals',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:20',
    defaultSets: 6,
    defaultRest: '00:40',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'All-out effort. Full recovery between reps.',
    categories: ['hiit'],
  },
  {
    name: 'Rowing Machine Intervals',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 5,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Max effort strokes. Focus on power from legs first.',
    categories: ['hiit', 'cross'],
  },
]

// ─── CROSS TRAINING ──────────────────────────────────────────────────────────

const crossTrainingExercises: SeedExercise[] = [
  {
    name: 'Plank',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:45',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Forearms or hands. Straight line from head to heels. No sagging.',
    categories: ['cross', 'strength'],
  },
  {
    name: 'Side Plank',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Stack hips. Keep body in a straight line.',
    categories: ['cross', 'strength'],
  },
  {
    name: 'Dead Bug',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Lower back pressed into floor throughout. Slow and controlled.',
    categories: ['cross'],
  },
  {
    name: 'Bird Dog',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Opposite arm and leg extend. Keep hips level.',
    categories: ['cross'],
  },
  {
    name: 'Glute Bridge',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '15',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Squeeze glutes at top. Pause 1-2 seconds. Don\'t hyperextend lower back.',
    categories: ['cross', 'strength'],
  },
  {
    name: 'Single-Leg Glute Bridge',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each leg. Keep hips level. Slow controlled descent.',
    categories: ['cross', 'strength'],
  },
  {
    name: 'Clamshells',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '15',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Band above knees if available. Rotate from hip, feet stay together.',
    categories: ['cross'],
  },
  {
    name: 'Russian Twist',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '20',
    defaultSets: 3,
    defaultRest: '00:45',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Total reps (L+R = 1). Lean back slightly, rotate from core not arms.',
    categories: ['cross'],
  },
  {
    name: 'Bicycle Crunches',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '20',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Slow and controlled. Opposite elbow to knee. Full leg extension.',
    categories: ['cross'],
  },
  {
    name: 'Superman Hold',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:20',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Face down. Lift arms and legs off floor. Squeeze glutes.',
    categories: ['cross'],
  },
  {
    name: 'Push-Ups',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Full range. Elbows at ~45°. Body straight throughout.',
    categories: ['cross', 'strength'],
  },
  {
    name: 'TRX Row',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Body straight. Pull chest to handles. Control the release.',
    categories: ['cross', 'strength'],
  },
  {
    name: 'Step-Ups',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each leg. Drive through front heel. Don\'t push off back foot.',
    categories: ['cross', 'strength'],
  },
  {
    name: 'Single-Leg Deadlift',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each leg. Hinge at hip, back leg extends behind. Balance and control.',
    categories: ['cross', 'strength'],
  },
  {
    name: 'Bear Crawl',
    demoVideo: 'https://www.youtube.com/watch?v=4d52Y9W2M0g',
    defaultMeasureType: 'distance',
    defaultMeasureValue: '20m',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Knees hovering just off ground. Opposite hand and foot move together.',
    categories: ['cross', 'hiit'],
  },
  {
    name: 'Wall Sit',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:45',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Back flat against wall. Thighs parallel to floor. Don\'t push on knees.',
    categories: ['cross', 'strength'],
  },
]

// ─── COMBINED EXPORT ─────────────────────────────────────────────────────────

export const SEED_EXERCISES: SeedExercise[] = [
  ...stretchingExercises,
  ...strengthExercises,
  ...hiitExercises,
  ...crossTrainingExercises,
]

export const SEED_EXERCISE_COUNT = SEED_EXERCISES.length
