/**
 * Seed Exercise Library
 * 
 * This is the curated default exercise library that ships with every new coach account.
 * Coaches can add demo video links themselves and also add their own custom exercises.
 * 
 * Categories covered: Stretching/Mobility, Strength, HIIT, Cross Training
 * 
 * Each exercise uses the same data shape as the exercise_library (templates table with
 * type='day', category='__exercise_library__').
 */

export type SeedExercise = {
  name: string
  demoVideo: string
  defaultMeasureType: 'reps' | 'time' | 'distance'
  defaultMeasureValue: string
  defaultSets: number
  defaultRest: string
  defaultWeight: string
  defaultWeightUnit: 'kg' | 'lbs'
  defaultNotes: string
}

// ─── STRETCHING / MOBILITY ───────────────────────────────────────────────────

const stretchingExercises: SeedExercise[] = [
  {
    name: 'Hip Flexor Stretch',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Keep hips square, gently push forward.',
  },
  {
    name: 'Pigeon Stretch',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:45',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Sink into the stretch gradually.',
  },
  {
    name: 'Hamstring Stretch (Standing)',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Hinge at hips, keep back flat.',
  },
  {
    name: 'Quad Stretch (Standing)',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Keep knees together, hold something for balance if needed.',
  },
  {
    name: 'Calf Stretch (Wall)',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Straight back leg, heel pressed down.',
  },
  {
    name: 'Cat-Cow',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Slow controlled movement. Breathe in on cow, out on cat.',
  },
  {
    name: 'World\'s Greatest Stretch',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '5',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Lunge, rotate, reach. Full range of motion.',
  },
  {
    name: 'Thoracic Spine Rotation',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. On all fours, hand behind head, rotate open.',
  },
  {
    name: 'Foam Roll — IT Band',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:45',
    defaultSets: 1,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Slow rolls from hip to just above knee.',
  },
  {
    name: 'Foam Roll — Quads',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:45',
    defaultSets: 1,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Face down. Roll from hip to above kneecap.',
  },
  {
    name: 'Foam Roll — Upper Back',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:45',
    defaultSets: 1,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Arms crossed over chest. Roll mid to upper back.',
  },
  {
    name: '90/90 Hip Stretch',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Sit tall, lean into front hip.',
  },
  {
    name: 'Downward Dog',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Pedal feet to loosen calves. Push hips high.',
  },
  {
    name: 'Banded Shoulder Dislocates',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 2,
    defaultRest: '00:15',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Wide grip. Slow controlled arc over and behind head.',
  },
]

// ─── STRENGTH ────────────────────────────────────────────────────────────────

const strengthExercises: SeedExercise[] = [
  {
    name: 'Barbell Back Squat',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 4,
    defaultRest: '02:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Brace core. Break at hips and knees together. Depth to parallel or below.',
  },
  {
    name: 'Goblet Squat',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Hold dumbbell at chest. Elbows inside knees at bottom.',
  },
  {
    name: 'Romanian Deadlift (RDL)',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Soft knees, hinge at hips. Feel stretch in hamstrings. Bar/DB stays close to legs.',
  },
  {
    name: 'Conventional Deadlift',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '5',
    defaultSets: 4,
    defaultRest: '02:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Flat back, brace core. Drive through floor. Lockout hips at top.',
  },
  {
    name: 'Walking Lunges',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each leg. Long stride, back knee close to floor.',
  },
  {
    name: 'Bulgarian Split Squat',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each leg. Rear foot elevated on bench. Upright torso.',
  },
  {
    name: 'Bench Press (Barbell)',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 4,
    defaultRest: '02:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Shoulder blades pinched. Bar to chest, drive up. Feet flat on floor.',
  },
  {
    name: 'Dumbbell Bench Press',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Full range of motion. Control the descent.',
  },
  {
    name: 'Overhead Press (Barbell)',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 3,
    defaultRest: '02:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Brace core tight. Press straight up, head through at top.',
  },
  {
    name: 'Dumbbell Shoulder Press',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Seated or standing. Full lockout overhead.',
  },
  {
    name: 'Bent-Over Row (Barbell)',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Hinge forward ~45°. Pull to lower chest. Squeeze shoulder blades.',
  },
  {
    name: 'Single-Arm Dumbbell Row',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each arm. Pull elbow back past torso. No rotation.',
  },
  {
    name: 'Pull-Ups',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 3,
    defaultRest: '02:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Full hang to chin over bar. Control the descent.',
  },
  {
    name: 'Lat Pulldown',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Wide grip. Pull to upper chest. Squeeze lats at bottom.',
  },
  {
    name: 'Hip Thrust',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Upper back on bench. Drive hips to full extension. Squeeze glutes at top.',
  },
  {
    name: 'Leg Press',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Feet shoulder width. Full depth without lower back lifting.',
  },
  {
    name: 'Calf Raises (Standing)',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '15',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Full range — stretch at bottom, pause at top. Slow tempo.',
  },
  {
    name: 'Face Pulls',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '15',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Pull to eye level, externally rotate at end. Light weight, squeeze rear delts.',
  },
  {
    name: 'Lateral Raises',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Slight bend in elbows. Raise to shoulder height, control down.',
  },
  {
    name: 'Bicep Curls (Dumbbell)',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'No swinging. Full extension at bottom, squeeze at top.',
  },
  {
    name: 'Tricep Dips',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Bench dips or parallel bars. Elbows back, not flared.',
  },
]

// ─── HIIT ────────────────────────────────────────────────────────────────────

const hiitExercises: SeedExercise[] = [
  {
    name: 'Burpees',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Chest to floor, jump at top. Keep moving.',
  },
  {
    name: 'Mountain Climbers',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Fast pace. Hips level, core tight.',
  },
  {
    name: 'Jump Squats',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Squat to parallel, explode up. Soft landing.',
  },
  {
    name: 'Box Jumps',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Land softly with both feet fully on box. Step down.',
  },
  {
    name: 'Kettlebell Swings',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '15',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Hip hinge, not a squat. Snap hips forward. Arms are just along for the ride.',
  },
  {
    name: 'Battle Ropes — Alternating Waves',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Slight squat stance. Fast alternating arms. Keep waves consistent.',
  },
  {
    name: 'High Knees',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Drive knees to hip height. Pump arms. Stay on balls of feet.',
  },
  {
    name: 'Tuck Jumps',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Jump and drive knees to chest. Land soft.',
  },
  {
    name: 'Skater Jumps',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '00:45',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side counts as 1. Bound laterally, land on one leg.',
  },
  {
    name: 'Thruster (Dumbbell)',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Front squat into overhead press in one fluid movement.',
  },
  {
    name: 'Sprint Intervals',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:20',
    defaultSets: 6,
    defaultRest: '00:40',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'All-out effort. Full recovery between reps.',
  },
  {
    name: 'Rowing Machine Intervals',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 5,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Max effort strokes. Focus on power from legs first.',
  },
]

// ─── CROSS TRAINING ──────────────────────────────────────────────────────────

const crossTrainingExercises: SeedExercise[] = [
  {
    name: 'Plank',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:45',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Forearms or hands. Straight line from head to heels. No sagging.',
  },
  {
    name: 'Side Plank',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:30',
    defaultSets: 2,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Stack hips. Keep body in a straight line.',
  },
  {
    name: 'Dead Bug',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Lower back pressed into floor throughout. Slow and controlled.',
  },
  {
    name: 'Bird Dog',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Opposite arm and leg extend. Keep hips level.',
  },
  {
    name: 'Glute Bridge',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '15',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Squeeze glutes at top. Pause 1-2 seconds. Don\'t hyperextend lower back.',
  },
  {
    name: 'Single-Leg Glute Bridge',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each leg. Keep hips level. Slow controlled descent.',
  },
  {
    name: 'Clamshells',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '15',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each side. Band above knees if available. Rotate from hip, feet stay together.',
  },
  {
    name: 'Russian Twist',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '20',
    defaultSets: 3,
    defaultRest: '00:45',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Total reps (L+R = 1). Lean back slightly, rotate from core not arms.',
  },
  {
    name: 'Bicycle Crunches',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '20',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Slow and controlled. Opposite elbow to knee. Full leg extension.',
  },
  {
    name: 'Superman Hold',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:20',
    defaultSets: 3,
    defaultRest: '00:30',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Face down. Lift arms and legs off floor. Squeeze glutes.',
  },
  {
    name: 'Push-Ups',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Full range. Elbows at ~45°. Body straight throughout.',
  },
  {
    name: 'TRX Row',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '12',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Body straight. Pull chest to handles. Control the release.',
  },
  {
    name: 'Step-Ups',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '10',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each leg. Drive through front heel. Don\'t push off back foot.',
  },
  {
    name: 'Single-Leg Deadlift',
    demoVideo: '',
    defaultMeasureType: 'reps',
    defaultMeasureValue: '8',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Each leg. Hinge at hip, back leg extends behind. Balance and control.',
  },
  {
    name: 'Bear Crawl',
    demoVideo: '',
    defaultMeasureType: 'distance',
    defaultMeasureValue: '20m',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Knees hovering just off ground. Opposite hand and foot move together.',
  },
  {
    name: 'Wall Sit',
    demoVideo: '',
    defaultMeasureType: 'time',
    defaultMeasureValue: '0:45',
    defaultSets: 3,
    defaultRest: '01:00',
    defaultWeight: '',
    defaultWeightUnit: 'kg',
    defaultNotes: 'Back flat against wall. Thighs parallel to floor. Don\'t push on knees.',
  },
]

// ─── COMBINED EXPORT ─────────────────────────────────────────────────────────

export const SEED_EXERCISES: SeedExercise[] = [
  ...stretchingExercises,
  ...strengthExercises,
  ...hiitExercises,
  ...crossTrainingExercises,
]

export const SEED_EXERCISE_COUNT = SEED_EXERCISES.length
