-- Seed Exercise Library for Existing Coaches
-- Run this ONCE in your Supabase SQL Editor to add the default exercises
-- to all organizations that don't already have exercise library entries.
--
-- Safe to run multiple times — it skips orgs that already have exercises.

DO $$
DECLARE
  org RECORD;
BEGIN
  -- Loop through all organizations that have NO exercise library entries
  FOR org IN
    SELECT o.id, o.name
    FROM public.organizations o
    WHERE NOT EXISTS (
      SELECT 1 FROM public.templates t
      WHERE t.organization_id = o.id
        AND t.type = 'day'
        AND t.category = '__exercise_library__'
    )
  LOOP
    RAISE NOTICE 'Seeding exercises for org: % (%)', org.name, org.id;

    INSERT INTO public.templates (name, type, category, organization_id, data)
    VALUES
      ('Hip Flexor Stretch', 'day', '__exercise_library__', org.id, '{"name":"Hip Flexor Stretch","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:30","defaultSets":2,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. Keep hips square, gently push forward."}'::jsonb),
      ('Pigeon Stretch', 'day', '__exercise_library__', org.id, '{"name":"Pigeon Stretch","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:45","defaultSets":2,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. Sink into the stretch gradually."}'::jsonb),
      ('Hamstring Stretch (Standing)', 'day', '__exercise_library__', org.id, '{"name":"Hamstring Stretch (Standing)","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:30","defaultSets":2,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. Hinge at hips, keep back flat."}'::jsonb),
      ('Quad Stretch (Standing)', 'day', '__exercise_library__', org.id, '{"name":"Quad Stretch (Standing)","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:30","defaultSets":2,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. Keep knees together, hold something for balance if needed."}'::jsonb),
      ('Calf Stretch (Wall)', 'day', '__exercise_library__', org.id, '{"name":"Calf Stretch (Wall)","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:30","defaultSets":2,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. Straight back leg, heel pressed down."}'::jsonb),
      ('Cat-Cow', 'day', '__exercise_library__', org.id, '{"name":"Cat-Cow","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":2,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Slow controlled movement. Breathe in on cow, out on cat."}'::jsonb),
      ('World''s Greatest Stretch', 'day', '__exercise_library__', org.id, '{"name":"World''s Greatest Stretch","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"5","defaultSets":2,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. Lunge, rotate, reach. Full range of motion."}'::jsonb),
      ('Thoracic Spine Rotation', 'day', '__exercise_library__', org.id, '{"name":"Thoracic Spine Rotation","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"8","defaultSets":2,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. On all fours, hand behind head, rotate open."}'::jsonb),
      ('Foam Roll — IT Band', 'day', '__exercise_library__', org.id, '{"name":"Foam Roll — IT Band","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:45","defaultSets":1,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. Slow rolls from hip to just above knee."}'::jsonb),
      ('Foam Roll — Quads', 'day', '__exercise_library__', org.id, '{"name":"Foam Roll — Quads","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:45","defaultSets":1,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Face down. Roll from hip to above kneecap."}'::jsonb),
      ('Foam Roll — Upper Back', 'day', '__exercise_library__', org.id, '{"name":"Foam Roll — Upper Back","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:45","defaultSets":1,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Arms crossed over chest. Roll mid to upper back."}'::jsonb),
      ('90/90 Hip Stretch', 'day', '__exercise_library__', org.id, '{"name":"90/90 Hip Stretch","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:30","defaultSets":2,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. Sit tall, lean into front hip."}'::jsonb),
      ('Downward Dog', 'day', '__exercise_library__', org.id, '{"name":"Downward Dog","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:30","defaultSets":2,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Pedal feet to loosen calves. Push hips high."}'::jsonb),
      ('Banded Shoulder Dislocates', 'day', '__exercise_library__', org.id, '{"name":"Banded Shoulder Dislocates","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":2,"defaultRest":"00:15","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Wide grip. Slow controlled arc over and behind head."}'::jsonb),
      ('Barbell Back Squat', 'day', '__exercise_library__', org.id, '{"name":"Barbell Back Squat","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"8","defaultSets":4,"defaultRest":"02:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Brace core. Break at hips and knees together. Depth to parallel or below."}'::jsonb),
      ('Goblet Squat', 'day', '__exercise_library__', org.id, '{"name":"Goblet Squat","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"12","defaultSets":3,"defaultRest":"01:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Hold dumbbell at chest. Elbows inside knees at bottom."}'::jsonb),
      ('Romanian Deadlift (RDL)', 'day', '__exercise_library__', org.id, '{"name":"Romanian Deadlift (RDL)","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":3,"defaultRest":"01:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Soft knees, hinge at hips. Feel stretch in hamstrings. Bar/DB stays close to legs."}'::jsonb),
      ('Conventional Deadlift', 'day', '__exercise_library__', org.id, '{"name":"Conventional Deadlift","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"5","defaultSets":4,"defaultRest":"02:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Flat back, brace core. Drive through floor. Lockout hips at top."}'::jsonb),
      ('Walking Lunges', 'day', '__exercise_library__', org.id, '{"name":"Walking Lunges","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"12","defaultSets":3,"defaultRest":"01:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each leg. Long stride, back knee close to floor."}'::jsonb),
      ('Bulgarian Split Squat', 'day', '__exercise_library__', org.id, '{"name":"Bulgarian Split Squat","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":3,"defaultRest":"01:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each leg. Rear foot elevated on bench. Upright torso."}'::jsonb),
      ('Bench Press (Barbell)', 'day', '__exercise_library__', org.id, '{"name":"Bench Press (Barbell)","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"8","defaultSets":4,"defaultRest":"02:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Shoulder blades pinched. Bar to chest, drive up. Feet flat on floor."}'::jsonb),
      ('Dumbbell Bench Press', 'day', '__exercise_library__', org.id, '{"name":"Dumbbell Bench Press","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":3,"defaultRest":"01:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Full range of motion. Control the descent."}'::jsonb),
      ('Overhead Press (Barbell)', 'day', '__exercise_library__', org.id, '{"name":"Overhead Press (Barbell)","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"8","defaultSets":3,"defaultRest":"02:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Brace core tight. Press straight up, head through at top."}'::jsonb),
      ('Dumbbell Shoulder Press', 'day', '__exercise_library__', org.id, '{"name":"Dumbbell Shoulder Press","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":3,"defaultRest":"01:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Seated or standing. Full lockout overhead."}'::jsonb),
      ('Bent-Over Row (Barbell)', 'day', '__exercise_library__', org.id, '{"name":"Bent-Over Row (Barbell)","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":3,"defaultRest":"01:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Hinge forward ~45°. Pull to lower chest. Squeeze shoulder blades."}'::jsonb),
      ('Single-Arm Dumbbell Row', 'day', '__exercise_library__', org.id, '{"name":"Single-Arm Dumbbell Row","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each arm. Pull elbow back past torso. No rotation."}'::jsonb),
      ('Pull-Ups', 'day', '__exercise_library__', org.id, '{"name":"Pull-Ups","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"8","defaultSets":3,"defaultRest":"02:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Full hang to chin over bar. Control the descent."}'::jsonb),
      ('Lat Pulldown', 'day', '__exercise_library__', org.id, '{"name":"Lat Pulldown","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"12","defaultSets":3,"defaultRest":"01:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Wide grip. Pull to upper chest. Squeeze lats at bottom."}'::jsonb),
      ('Hip Thrust', 'day', '__exercise_library__', org.id, '{"name":"Hip Thrust","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"12","defaultSets":3,"defaultRest":"01:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Upper back on bench. Drive hips to full extension. Squeeze glutes at top."}'::jsonb),
      ('Leg Press', 'day', '__exercise_library__', org.id, '{"name":"Leg Press","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"12","defaultSets":3,"defaultRest":"01:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Feet shoulder width. Full depth without lower back lifting."}'::jsonb),
      ('Calf Raises (Standing)', 'day', '__exercise_library__', org.id, '{"name":"Calf Raises (Standing)","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"15","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Full range — stretch at bottom, pause at top. Slow tempo."}'::jsonb),
      ('Face Pulls', 'day', '__exercise_library__', org.id, '{"name":"Face Pulls","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"15","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Pull to eye level, externally rotate at end. Light weight, squeeze rear delts."}'::jsonb),
      ('Lateral Raises', 'day', '__exercise_library__', org.id, '{"name":"Lateral Raises","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"12","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Slight bend in elbows. Raise to shoulder height, control down."}'::jsonb),
      ('Bicep Curls (Dumbbell)', 'day', '__exercise_library__', org.id, '{"name":"Bicep Curls (Dumbbell)","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"12","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"No swinging. Full extension at bottom, squeeze at top."}'::jsonb),
      ('Tricep Dips', 'day', '__exercise_library__', org.id, '{"name":"Tricep Dips","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"12","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Bench dips or parallel bars. Elbows back, not flared."}'::jsonb),
      ('Burpees', 'day', '__exercise_library__', org.id, '{"name":"Burpees","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Chest to floor, jump at top. Keep moving."}'::jsonb),
      ('Mountain Climbers', 'day', '__exercise_library__', org.id, '{"name":"Mountain Climbers","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:30","defaultSets":3,"defaultRest":"00:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Fast pace. Hips level, core tight."}'::jsonb),
      ('Jump Squats', 'day', '__exercise_library__', org.id, '{"name":"Jump Squats","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"12","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Squat to parallel, explode up. Soft landing."}'::jsonb),
      ('Box Jumps', 'day', '__exercise_library__', org.id, '{"name":"Box Jumps","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"8","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Land softly with both feet fully on box. Step down."}'::jsonb),
      ('Kettlebell Swings', 'day', '__exercise_library__', org.id, '{"name":"Kettlebell Swings","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"15","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Hip hinge, not a squat. Snap hips forward. Arms are just along for the ride."}'::jsonb),
      ('Battle Ropes — Alternating Waves', 'day', '__exercise_library__', org.id, '{"name":"Battle Ropes — Alternating Waves","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:30","defaultSets":3,"defaultRest":"00:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Slight squat stance. Fast alternating arms. Keep waves consistent."}'::jsonb),
      ('High Knees', 'day', '__exercise_library__', org.id, '{"name":"High Knees","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:30","defaultSets":3,"defaultRest":"00:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Drive knees to hip height. Pump arms. Stay on balls of feet."}'::jsonb),
      ('Tuck Jumps', 'day', '__exercise_library__', org.id, '{"name":"Tuck Jumps","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"8","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Jump and drive knees to chest. Land soft."}'::jsonb),
      ('Skater Jumps', 'day', '__exercise_library__', org.id, '{"name":"Skater Jumps","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"12","defaultSets":3,"defaultRest":"00:45","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side counts as 1. Bound laterally, land on one leg."}'::jsonb),
      ('Thruster (Dumbbell)', 'day', '__exercise_library__', org.id, '{"name":"Thruster (Dumbbell)","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Front squat into overhead press in one fluid movement."}'::jsonb),
      ('Sprint Intervals', 'day', '__exercise_library__', org.id, '{"name":"Sprint Intervals","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:20","defaultSets":6,"defaultRest":"00:40","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"All-out effort. Full recovery between reps."}'::jsonb),
      ('Rowing Machine Intervals', 'day', '__exercise_library__', org.id, '{"name":"Rowing Machine Intervals","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:30","defaultSets":5,"defaultRest":"00:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Max effort strokes. Focus on power from legs first."}'::jsonb),
      ('Plank', 'day', '__exercise_library__', org.id, '{"name":"Plank","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:45","defaultSets":3,"defaultRest":"00:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Forearms or hands. Straight line from head to heels. No sagging."}'::jsonb),
      ('Side Plank', 'day', '__exercise_library__', org.id, '{"name":"Side Plank","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:30","defaultSets":2,"defaultRest":"00:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. Stack hips. Keep body in a straight line."}'::jsonb),
      ('Dead Bug', 'day', '__exercise_library__', org.id, '{"name":"Dead Bug","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":3,"defaultRest":"00:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. Lower back pressed into floor throughout. Slow and controlled."}'::jsonb),
      ('Bird Dog', 'day', '__exercise_library__', org.id, '{"name":"Bird Dog","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":3,"defaultRest":"00:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. Opposite arm and leg extend. Keep hips level."}'::jsonb),
      ('Glute Bridge', 'day', '__exercise_library__', org.id, '{"name":"Glute Bridge","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"15","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Squeeze glutes at top. Pause 1-2 seconds. Don''t hyperextend lower back."}'::jsonb),
      ('Single-Leg Glute Bridge', 'day', '__exercise_library__', org.id, '{"name":"Single-Leg Glute Bridge","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each leg. Keep hips level. Slow controlled descent."}'::jsonb),
      ('Clamshells', 'day', '__exercise_library__', org.id, '{"name":"Clamshells","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"15","defaultSets":3,"defaultRest":"00:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each side. Band above knees if available. Rotate from hip, feet stay together."}'::jsonb),
      ('Russian Twist', 'day', '__exercise_library__', org.id, '{"name":"Russian Twist","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"20","defaultSets":3,"defaultRest":"00:45","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Total reps (L+R = 1). Lean back slightly, rotate from core not arms."}'::jsonb),
      ('Bicycle Crunches', 'day', '__exercise_library__', org.id, '{"name":"Bicycle Crunches","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"20","defaultSets":3,"defaultRest":"00:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Slow and controlled. Opposite elbow to knee. Full leg extension."}'::jsonb),
      ('Superman Hold', 'day', '__exercise_library__', org.id, '{"name":"Superman Hold","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:20","defaultSets":3,"defaultRest":"00:30","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Face down. Lift arms and legs off floor. Squeeze glutes."}'::jsonb),
      ('Push-Ups', 'day', '__exercise_library__', org.id, '{"name":"Push-Ups","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"12","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Full range. Elbows at ~45°. Body straight throughout."}'::jsonb),
      ('TRX Row', 'day', '__exercise_library__', org.id, '{"name":"TRX Row","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"12","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Body straight. Pull chest to handles. Control the release."}'::jsonb),
      ('Step-Ups', 'day', '__exercise_library__', org.id, '{"name":"Step-Ups","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"10","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each leg. Drive through front heel. Don''t push off back foot."}'::jsonb),
      ('Single-Leg Deadlift', 'day', '__exercise_library__', org.id, '{"name":"Single-Leg Deadlift","demoVideo":"","defaultMeasureType":"reps","defaultMeasureValue":"8","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Each leg. Hinge at hip, back leg extends behind. Balance and control."}'::jsonb),
      ('Bear Crawl', 'day', '__exercise_library__', org.id, '{"name":"Bear Crawl","demoVideo":"","defaultMeasureType":"distance","defaultMeasureValue":"20m","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Knees hovering just off ground. Opposite hand and foot move together."}'::jsonb),
      ('Wall Sit', 'day', '__exercise_library__', org.id, '{"name":"Wall Sit","demoVideo":"","defaultMeasureType":"time","defaultMeasureValue":"0:45","defaultSets":3,"defaultRest":"01:00","defaultWeight":"","defaultWeightUnit":"kg","defaultNotes":"Back flat against wall. Thighs parallel to floor. Don''t push on knees."}'::jsonb);

  END LOOP;
END $$;

